org: brunopalollato
app: blog
service: serverless-crud

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: posts
          method: post
          cors: true
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: posts
          method: get
          cors: true
  readOne:
    handler: handler.readOne
    events:
      - http:
          path: posts/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: posts/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: posts/{id}
          method: delete
          cors: true

resources:
  Resources:
    postsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'posts'
